MollisHome/Web/MollisHome.Web/Areas/Dashboard/Controllers/ColorsController.cs
namespace MollisHome.Web.Areas.Dashboard.Controllers
{
    using AutoMapper;

    using MollisHome.Services.Data.Colors;
    using MollisHome.Services.DTOs.Colors;
    using MollisHome.Web.InputModels.Colors;

    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Authorization;

    using System.Threading.Tasks;

    [Area("Dashboard")]
    [Authorize(Roles = "Admin")]
    public class ColorsController : Controller
    {
        //---------------- FIELDS -----------------
        private readonly IMapper mapper;
        private readonly IColorsService colorsService;

        //------------- CONSTRUCTORS --------------
        public ColorsController(IMapper mapper, IColorsService colorsService)
        {
            this.mapper = mapper;
            this.colorsService = colorsService;
        }

        //-----------------------------------------------------------------------------------------------------//
        //                                           ACTION METHODS                                            //
        //-----------------------------------------------------------------------------------------------------//

        [HttpPost]
        public async Task<IActionResult> Create(ColorIM color)
        {
            if (!ModelState.IsValid)
            {
                return this.RedirectToAction("Create", "Products"); // have to redirect and then open the modal with new colors or smth
            }

            ColorDTO colorDTO = new ColorDTO
            {
                Name = color.Name,
                HexValue = color.HexValue,
            };

            string message = await this.colorsService.CreateAsync(colorDTO);
            this.TempData["ActionMessage"] = message;
            return this.RedirectToAction("Create", "Products");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            string message = await this.colorsService.DeleteAsync(id);
            this.TempData["ActionMessage"] = message;
            return this.RedirectToAction("Create", "Products");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ColorIM color)
        {
            if (!ModelState.IsValid)
            {
                return this.RedirectToAction("Create", "Products"); // have to redirect and then open the modal with new colors or smth
            }

            ColorDTO colorDTO = new ColorDTO
            {
                Id = color.Id,
                Name = color.Name,
                HexValue = color.HexValue,
            };

            string message = await this.colorsService.EditAsync(colorDTO);
            this.TempData["ActionMessage"] = message;
            return this.RedirectToAction("Create", "Products"); // have to redirect and then open the modal with new colors or smth
        }

        //----------------------- VALIDATIONS --------------------------
        [AcceptVerbs("GET", "POST")]
        public IActionResult VerifyName(string name)
        {
            if (this.colorsService.GetByName(name) != null) // TODO: Add exists method with overloads for different props
            {
                return this.Json($"Цвят с името '{name}' вече съществува.");
            }

            return this.Json(true);
        }
    }
}

MollisHome/Web/MollisHome.Web/Areas/Dashboard/Views/Colors/_All.cshtml
@model ColorIM

@{
  List<ColorVM> colors = Model.Colors.ToList();
}

@*------------------------- COLORS MODAL -------------------------*@
<!-- Button trigger modal -->
<button id="colors-pallete-btn" type="button" class="btn btn-info" data-toggle="modal" data-target="#colors">Цветова Палитра</button>

<!-- Modal -->
<div class="modal fade bd-example-modal-lg" id="colors" tabindex="-1" role="dialog" aria-labelledby="colorsModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="colorsModalLabel"><strong>Цветова Палитра</strong></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div id="colors-modal" class="modal-body">

        <!-- TABLE WITH COLORS -->
        <form method="post" asp-area="Dashboard" asp-controller="Colors" asp-action="Create">
          <table class="table table-bordered table-hover table-sm">
            <thead>
              <tr>
                <th scope="col">№</th>
                <th scope="col">Цвят</th>
                <th scope="col">Стойност</th>
                <th scope="col" style="text-align: center;">Опции</th>
              </tr>
            </thead>
            <tbody id="colors-table-body">
              @for (int i = 0; i < colors.Count; i++)
              {
                <tr>
                  <td>@(i + 1)</td>
                  <td>@colors[i].Name</td>
                  <td>@colors[i].HexValue</td>
                  <td style="text-align: center;">
                    <partial name="../Colors/_EditModal.cshtml" model="@new ColorIM() { Id = colors[i].Id, Name = colors[i].Name, HexValue = colors[i].HexValue }" />
                    <partial name="../Colors/_DeleteModalWarning.cshtml" model="colors[i]" />
                  </td>
                </tr>
              }
              <tr id="creation-row" style="display: none;">
                <td>@(colors.Count + 1)</td>
                <td>
                  <input id="color-name" asp-for="Name" type="text" placeholder="Name" class="form-control" />
                </td>

                <td>
                  <input id="color-hex" asp-for="HexValue" type="text" placeholder="HexValue" class="form-control" />
                </td>

                <td style="text-align: center;">
                  <button type="submit" class="btn btn-success">Добави</button>
                  <button id="cancel" type="button" class="btn btn-danger">Премахни</button>
                </td>
              </tr>
            </tbody>
          </table>

          <span id="color-name-msg" asp-validation-for="Name" class="text-danger"></span><br />
          <span id="color-hex-msg" asp-validation-for="HexValue" class="text-danger"></span>

        </form>

        <button id="create-color-btn" type="button" class="btn btn-warning">➕ Нов цвят</button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Затвори</button>
      </div>
    </div>
  </div>
</div>

MollisHome/Web/MollisHome.Web/Areas/Dashboard/Views/Colors/_DeleteModalWarning.cshtml
@model ColorVM
<!-- Button trigger modal -->
<button type="button" class="btn btn-outline-danger" data-toggle="modal" data-target="#delete@(Model.Id)">Изтрий</button>

<!-- Modal -->
<div class="modal fade" id="delete@(Model.Id)" tabindex="-1" role="dialog" aria-labelledby="warningModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="warningModalLabel">Сигурни ли сте че желаете да изтриете цвета <strong>@Model.Name - @Model.HexValue</strong>?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Допълнителна информация за CASCADE DELETE, която да уведоми ADMIN-а какво точно ще предизвика това действие.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Затвори</button>
        <form method="post">
          <button type="submit" class="btn btn-danger" asp-area="Dashboard" asp-controller="Colors" asp-action="Delete" asp-route-id="@Model.Id">Изтрий</button>
        </form>
      </div>
    </div>
  </div>

  @*<div class="modal-backdrop fade show"></div> AFTER OPENING *@
</div>

MollisHome/Web/MollisHome.Web/Areas/Dashboard/Views/Colors/_EditModal.cshtml
@model ColorIM
<!-- Button trigger modal -->
<button type="button" class="btn btn-outline-success" data-toggle="modal" data-target="#edit@(Model.Id)">Промени</button>

<!-- Modal -->
<div class="modal fade" id="edit@(Model.Id)" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editModalLabel">Промяна на информацията за цвета <strong>@Model.Name - @Model.HexValue</strong>?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <fieldset class="border p-3">
          <legend class="w-auto">Промяна на информация за цвят</legend>
          <form method="post" asp-area="Dashboard" asp-controller="Colors" asp-action="Edit">
            <p class="form-group">
              <label asp-for="Name"></label>
              <input asp-for="Name" type="text" placeholder="Name" class="form-control" />
              <span asp-validation-for="Name" class="text-danger"></span>
            </p>

            <p class="form-group">
              <label asp-for="HexValue"></label>
              <input asp-for="HexValue" type="text" placeholder="HexValue" class="form-control" />
              <span asp-validation-for="HexValue" class="text-danger"></span>
            </p>

            <button type="submit" class="btn btn-success" asp-area="Dashboard" asp-controller="Colors" asp-action="Edit" asp-route-id="@Model.Id">Промени</button>
          </form>
        </fieldset>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Отказ</button>
      </div>
    </div>
  </div>

  @*<div class="modal-backdrop fade show"></div> AFTER OPENING *@
</div>